# SPDX-FileCopyrightText: 2026 Adam Fidel
# SPDX-License-Identifier: MIT

"""Python binding for libarcana, an implementation of the Arcana Land tarot specs.
"""

from ._core import (
    __version__,
    arcana_kind,
    card,
    card_back_design,
    card_class,
    card_id,
    card_image,
    card_variant,
    deck,
    deck_error,
    deck_library,
    deck_library_path,
    deck_metadata,
    deck_summary,
    deck_summary_view,
    error,
    error_code,
    image_kind,
    is_valid_identifier,
    library_options,
    load_deck,
    malformed_deck,
    origin_term,
    rank,
    rank_from_string,
    schema_major,
    suit,
    suit_from_string,
    suit_info,
    to_string,
)

__all__ = [
    "__version__",
    "arcana_kind",
    "card",
    "card_back_design",
    "card_class",
    "card_id",
    "card_image",
    "card_variant",
    "deck",
    "deck_error",
    "deck_library",
    "deck_library_path",
    "deck_metadata",
    "deck_summary",
    "deck_summary_view",
    "error",
    "error_code",
    "image_kind",
    "is_valid_identifier",
    "library_options",
    "load_deck",
    "malformed_deck",
    "origin_term",
    "rank",
    "rank_from_string",
    "schema_major",
    "suit",
    "suit_from_string",
    "suit_info",
    "to_string",
]
